<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'GianFranco',
                'email' => 'Gian@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$k1auoB0YUcXdcQihVTHmeuDR3irqL7hhp2cwWAiWKmlgd91o2hMOy',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 02:22:08',
                'updated_at' => '2024-08-15 04:04:59',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Jhonatan',
                'email' => 'Jm@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YwBp.OzykM3oke2f8kxgqe5Y1sDj0AnR4d7/e.OBCFELX0oDdSkye',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 02:22:41',
                'updated_at' => '2024-08-15 04:05:19',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Fabian Ruiz',
                'email' => 'fruiz@mail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PRO.GF7682LwQsGwuE3Jru.geBFdHAOSN7hzZxSz/765Lw2Ru30Ia',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 06:40:55',
                'updated_at' => '2024-08-15 06:40:55',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Secretaria',
                'email' => 'secretaria@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.MYT.P7bnwPrQJeMKWEB9eiOnZUlz.DpShe/0kAMbC/EdJnVUc3nm',
                'remember_token' => NULL,
                'created_at' => '2024-11-21 05:53:17',
                'updated_at' => '2024-11-21 05:53:17',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Gian',
                'email' => 'gianfrancosr182015@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mpwkq3sT5DsGERrxbb8Hmux7sjOLxPKHMKf/hC3kHROLtzlwGS/I2',
                'remember_token' => NULL,
                'created_at' => '2024-11-24 21:42:45',
                'updated_at' => '2024-11-24 21:43:58',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'PRUEBA',
                'email' => 'mail@mail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4o3nfe4qNimZw.Sa.z8uf.T69xJvwz6eVJZaS9EMLtwprXlKKcv/a',
                'remember_token' => NULL,
                'created_at' => '2024-12-05 16:01:03',
                'updated_at' => '2024-12-05 16:01:03',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'ricardo.castro1',
                'email' => 'ricardo.castro1@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2x7IqpMt5.v4djwJNBHU6ORuLTyON8FN9Vj8ICy1AQd1DGZ8Q4i2a',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:51',
                'updated_at' => '2024-12-10 16:06:51',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'juan.pascual2',
                'email' => 'juan.pascual2@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OvUTtKoJAKtDvJ26OFzbuOZfFzAUOqVmIbme2rFt0iGk9nZ78UujC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:52',
                'updated_at' => '2024-12-10 16:06:52',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'josé.lópez3',
                'email' => 'josé.lópez3@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$QQvA6tmuPziZZZ9hGumMUOosCQqmGlHjSkaL27tns3VmmqlSMkos2',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:53',
                'updated_at' => '2024-12-10 16:06:53',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'beatriz.Álvarez4',
                'email' => 'beatriz.Álvarez4@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$UMHbT2zYbGJa6MSSWvA8KuPiqZZ/rVsUjgP97wawuvQ5wMl7XqzCW',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:54',
                'updated_at' => '2024-12-10 16:06:54',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'antonio.pascual5',
                'email' => 'antonio.pascual5@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qNcktL/amA3i5JeWAYQ6o.35MA.cjqs1kWpeV7jE.3TV/S4W4rSRG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:56',
                'updated_at' => '2024-12-10 16:06:56',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'isabel.díaz6',
                'email' => 'isabel.díaz6@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$msfBSLPb8g76zxD.g7AJDuLMyHqHJnb8Q55kt0O6RanfLDlg7FoUW',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:58',
                'updated_at' => '2024-12-10 16:06:58',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'victoria.gómez7',
                'email' => 'victoria.gómez7@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$gjdL0EMs7pcAPUB5uI.sOeq/mJH/Sy53KicAf3zrmMPUUQseSH3ZG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:06:59',
                'updated_at' => '2024-12-10 16:06:59',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'fernando.ortíz8',
                'email' => 'fernando.ortíz8@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Gp/xEAzkjz7JqRoSRws/COxmBc5tyG83LLIz2/DHgC./5nUV.1R06',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:00',
                'updated_at' => '2024-12-10 16:07:00',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'laura.moreno9',
                'email' => 'laura.moreno9@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$B.9PrF0/7GKH4Hg7e7RrKOLlUcYffR/q1NiKav0SGx/4Be6.MYn7m',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:02',
                'updated_at' => '2024-12-10 16:07:02',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'david.ortíz10',
                'email' => 'david.ortíz10@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$D1NJMDku6eqEYMjYnS604epjFuJn/4DlTgCp41W5WfDJvZfb1ngLu',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:03',
                'updated_at' => '2024-12-10 16:07:03',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'carmen.pascual11',
                'email' => 'carmen.pascual11@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IWUrdSxoT.0N.kZ4VxL/QOOEDK/FUo9YlamTZuoN9QY1/0KLs0Bfm',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:05',
                'updated_at' => '2024-12-10 16:07:05',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'carmen.lópez12',
                'email' => 'carmen.lópez12@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OSiHTJge5cK3IScdSHfJ9uzOiElX.n8Unx0D8VWGkVig2WRDCm7MC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:06',
                'updated_at' => '2024-12-10 16:07:06',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'pedro.ramos13',
                'email' => 'pedro.ramos13@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$r0A.r34WDYXfXBEZSYFqHOcyTOcsvfsDdaJN9k8hSWq7B0zdV4TUC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:07',
                'updated_at' => '2024-12-10 16:07:07',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'patricia.cabrera14',
                'email' => 'patricia.cabrera14@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$m3jtDgMugA39od9/o.romeEDvWzO6V2RMMMDCOvP1KRrTqiQKzUou',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:08',
                'updated_at' => '2024-12-10 16:07:08',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'lucía.navarro15',
                'email' => 'lucía.navarro15@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$UIxJVY8S1FezY5kqO46jWOLU6lXzXKEGrmVK/b1B4FYDdJlTtf7le',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:10',
                'updated_at' => '2024-12-10 16:07:10',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'ricardo.marín16',
                'email' => 'ricardo.marín16@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$bGB0SuLSyTgn6q1rRmEg9OMQ5Wx0DjkEIFr6lGZk8QIDzek4k8I1S',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:11',
                'updated_at' => '2024-12-10 16:07:11',
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'sofía.moreno17',
                'email' => 'sofía.moreno17@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$RIfULjtaovuITVg./BxlKe9C/N6yUuavJGPVGQK/PYoRTywgNErKW',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:12',
                'updated_at' => '2024-12-10 16:07:12',
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'juan.vázquez18',
                'email' => 'juan.vázquez18@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$QAd60N/wy0GEDd4rgDoKNeikOJGMvvLWiNkx1lZG0Mfxt4DgsQ84O',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:13',
                'updated_at' => '2024-12-10 16:07:13',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'carmen.gil19',
                'email' => 'carmen.gil19@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fD4HivXG86VWqxoIewb.BOprd8y0jw.PI/.PSFleWVyAJjQgeXtyG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:14',
                'updated_at' => '2024-12-10 16:07:14',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'carmen.gómez20',
                'email' => 'carmen.gómez20@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$FQcXSd8KP5np1rv5ifpe3.gES3I/IU1eAxn7qhenP0U4E9LEfaRa6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:16',
                'updated_at' => '2024-12-10 16:07:16',
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'luis.sánchez21',
                'email' => 'luis.sánchez21@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IkOYLz49aTh5SavuFwRZju.3hXSu6rdUlCEVobfJLLSG7SxyjEwpO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:17',
                'updated_at' => '2024-12-10 16:07:17',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'marta.díaz22',
                'email' => 'marta.díaz22@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$r/m6xeZK1zhqYpl5LaZQxOo0feJCcfOD.uhtOMzn5NixGze9Dq2jG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:18',
                'updated_at' => '2024-12-10 16:07:18',
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'luis.ramírez23',
                'email' => 'luis.ramírez23@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fgI/uJLLOgzxEH5nuDX/5uIw4Nzu6cmEDybLUs/87pnqlELNMnhQ6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:19',
                'updated_at' => '2024-12-10 16:07:19',
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'ana.navarro24',
                'email' => 'ana.navarro24@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$14sdJ1xd1ys/41rNm9XV5O7u4//hymZ54reg6OYs4VFxCMBsF47g2',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:20',
                'updated_at' => '2024-12-10 16:07:20',
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'isabel.muñoz25',
                'email' => 'isabel.muñoz25@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$KXJU.cRIE2hdSBTURfkjJOmV3kcLRqTt4h.GBs99czU4aUjYl3Wkm',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:21',
                'updated_at' => '2024-12-10 16:07:21',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'elena.ortíz26',
                'email' => 'elena.ortíz26@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NYUIKo1tXL1eQlEJjSwxD.tEpFJksn/ZfjOxuqEyxhSUlXSL3IwzC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:22',
                'updated_at' => '2024-12-10 16:07:22',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'raúl.serrano27',
                'email' => 'raúl.serrano27@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pPXPCM1zxhCmDVWfRyT2NOiq0sFS533JtkXB0NQSCwsXTp2sa6Gp6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:23',
                'updated_at' => '2024-12-10 16:07:23',
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'maría.méndez28',
                'email' => 'maría.méndez28@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$FJULZo0a74dL13WKjFqZNOBvtX13upDuajWdB3X8gcQzJYcD3rzba',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:24',
                'updated_at' => '2024-12-10 16:07:24',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'sofía.vázquez29',
                'email' => 'sofía.vázquez29@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$LQY1R3zuPAjHeJcdfvZgXuH71Dof23t.tNaS5e6M9xBa5WHUpdmc6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:25',
                'updated_at' => '2024-12-10 16:07:25',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'fernando.gómez30',
                'email' => 'fernando.gómez30@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Pmb0wcZEYvgaEBCD7TNITewouavj9lupubFnaMBb/mrM8rspNXbAi',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:27',
                'updated_at' => '2024-12-10 16:07:27',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'carlos.méndez31',
                'email' => 'carlos.méndez31@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NuHs5bRUsIA5hR4o.6u6gOCY5MamlAuxeCjYPLf5Fb5SWWpj0qXzm',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:28',
                'updated_at' => '2024-12-10 16:07:28',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'lucía.martínez32',
                'email' => 'lucía.martínez32@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GGmX59NDHINhvAafq1Mua.UPGurCkca9fmIfwqSyMqlh/fK3EkxXa',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:29',
                'updated_at' => '2024-12-10 16:07:29',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'miguel.salazar33',
                'email' => 'miguel.salazar33@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$h3FkyJvGNWg6NbFZfXRY6eeUYQIeKq9/Bw9EZyhW0F3tq8c4GeHtO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:30',
                'updated_at' => '2024-12-10 16:07:30',
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'sofía.hernández34',
                'email' => 'sofía.hernández34@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$z9WsQFGUCuKFtDGfdS6tnO3F/S2NShlFxnx.AjtD43M3V2z0JR8fi',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:29',
                'updated_at' => '2024-12-10 16:07:29',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'antonio.paredes35',
                'email' => 'antonio.paredes35@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$sSeiriJKl3BrybVapKyUAe42pvZRgcX48EWZwqL1yPzd617SKCN46',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:30',
                'updated_at' => '2024-12-10 16:07:30',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'maría.ramírez36',
                'email' => 'maría.ramírez36@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$q.Vwwlhs2E54E4un/q0NOe5wLqX8bGjGUHLxzV4EKxPRTTDDBNbgi',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:31',
                'updated_at' => '2024-12-10 16:07:31',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'sara.jiménez37',
                'email' => 'sara.jiménez37@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YzBOOakrVNsLpqGFZ5WF7.k9Wj3aLXW4pTm1P8toCFPtrT2lg7DlO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:32',
                'updated_at' => '2024-12-10 16:07:32',
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'beatriz.torres38',
                'email' => 'beatriz.torres38@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$iI0c98yWcIycRXxMCCIjQOqAycyuE..KxbelfpbraG3pFyTNfe3qK',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:33',
                'updated_at' => '2024-12-10 16:07:33',
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'carlos.méndez39',
                'email' => 'carlos.méndez39@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$42Xy1bSsRu3CDkRTwRd8/eoW47/DvpixiOtNv5RZzt/NO7c6Mijca',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:34',
                'updated_at' => '2024-12-10 16:07:34',
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'andrés.sánchez40',
                'email' => 'andrés.sánchez40@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$AXPHvSEWAJdzzaVBVsqFoeQM/WqIpJdduDEEfPGHBzgq/bAur./.W',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:35',
                'updated_at' => '2024-12-10 16:07:35',
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'carmen.serrano41',
                'email' => 'carmen.serrano41@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IcfrNgY3RPwCIW1/nAbZc.AosvBYu2NxMfoLXIjWZawDewYERVbau',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:36',
                'updated_at' => '2024-12-10 16:07:36',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'ana.Álvarez42',
                'email' => 'ana.Álvarez42@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3MRc4FAIceK.FsUm.uN3Z.yqvAtNcNcoAFShont.00aYtGdL/ZAtq',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:37',
                'updated_at' => '2024-12-10 16:07:37',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'pedro.paredes43',
                'email' => 'pedro.paredes43@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3xoAhSObim7m6rC8ZZB4Gedx.XW6cEJjbm.WVieGUbwMa4nOTMilC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:38',
                'updated_at' => '2024-12-10 16:07:38',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'elena.navarro44',
                'email' => 'elena.navarro44@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2WMuBI3XV5ffTBKBn5R5HufSctuleQo5KwHg8BDDyMrPcQ4j6HfCm',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:40',
                'updated_at' => '2024-12-10 16:07:40',
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'carmen.gil45',
                'email' => 'carmen.gil45@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$a3gClhZeJ0fdqMOHURMDWeC/450VFjjP2nKj7e7DYy2t9jLQoS.OW',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:41',
                'updated_at' => '2024-12-10 16:07:41',
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'pablo.sánchez46',
                'email' => 'pablo.sánchez46@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3ttumQGFmWho4qdJYCB2LegsLkNbJRg5wYfeykuSyPjZJf2hXFvy6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:42',
                'updated_at' => '2024-12-10 16:07:42',
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'fernando.ramos47',
                'email' => 'fernando.ramos47@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$dc0PKIcnPUwJWcq9ywRDfuhuP6pGQkoivhQOnRdca9rpOK186IMKq',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:43',
                'updated_at' => '2024-12-10 16:07:43',
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'laura.paredes48',
                'email' => 'laura.paredes48@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$bZkHy9QUj2F5wO/hag.dCeUmVLX5RXImiJPhw7yOwOCFEi96ML6gy',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:44',
                'updated_at' => '2024-12-10 16:07:44',
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'sara.moreno49',
                'email' => 'sara.moreno49@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9D3ecSjniFZ7t1lf9EBj9eVYAKo2/wGcyy6PSkHXMHPXqRxz37n0e',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:46',
                'updated_at' => '2024-12-10 16:07:46',
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'felipe.marín50',
                'email' => 'felipe.marín50@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$o/RFHhJYDXEgnU//L4gLSuLsYYzQn3iwR1I5CTlcvM6U1ha7A1wha',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:47',
                'updated_at' => '2024-12-10 16:07:47',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'patricia.moreno51',
                'email' => 'patricia.moreno51@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4BAlXP/Yxu9AuCNq/LfQke7S5QCPpRSIepsMyi4iy7OFVgs/bc4gC',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:48',
                'updated_at' => '2024-12-10 16:07:48',
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'ricardo.castro52',
                'email' => 'ricardo.castro52@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mkf2.CGcKduluo8xkkUhXOkUSs0FXbHCDNPGLe3FwEin8Ip2LwlTa',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:49',
                'updated_at' => '2024-12-10 16:07:49',
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'isabel.iglesias53',
                'email' => 'isabel.iglesias53@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$QF/x/HsmR8RYOLa3bVBG6uBJ4E6i8YBj0K0teuu2ocN.d2Ja4mzZu',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:50',
                'updated_at' => '2024-12-10 16:07:50',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'fernando.gil54',
                'email' => 'fernando.gil54@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.jhZNNLGmvtWVlYhdn1njOdsf5R.xbqW/Mu6RBII3WdfQ231Whgme',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:52',
                'updated_at' => '2024-12-10 16:07:52',
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'carlos.paredes55',
                'email' => 'carlos.paredes55@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$f1rL.AelVFRfP6z1Rjople.SRWW3Z7tLjfsP4VOJ1GKj.Fg0/dC8.',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:53',
                'updated_at' => '2024-12-10 16:07:53',
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'andrés.cruz56',
                'email' => 'andrés.cruz56@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$dMwYsvQdKQL8MzsALcYS8utvzEsRnao4Ea6F5LmagyxuaUYhokvaO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:54',
                'updated_at' => '2024-12-10 16:07:54',
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'andrés.Álvarez57',
                'email' => 'andrés.Álvarez57@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$C1nFEhdULPuQya6Qz2pqZOohcqJ.f3qCNBDMPrPSEUn6h8GH8I/9K',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:55',
                'updated_at' => '2024-12-10 16:07:55',
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'fernando.pascual58',
                'email' => 'fernando.pascual58@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fbPzLGujqIL2OP0jaPs.weImmch4DrnOj1kclonmd8Q29Y9DehgMO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:56',
                'updated_at' => '2024-12-10 16:07:56',
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'ricardo.pascual59',
                'email' => 'ricardo.pascual59@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$rnRD5tOwfJLwjCP8NgvANeejm06f5Bmwqy9Ji7x6kP/KHYCcnofw.',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:57',
                'updated_at' => '2024-12-10 16:07:57',
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'carmen.cruz60',
                'email' => 'carmen.cruz60@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$T8oxeTJStTlFtEcWV06MGePKe87TnISl4BeZkFjWfjqEHAOi2VV0a',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:59',
                'updated_at' => '2024-12-10 16:07:59',
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'ana.martínez61',
                'email' => 'ana.martínez61@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PuqNvj4/GAsJio.W7ajgX.lrV45vAbxv70SOD.Nm2TdLgIb441N3G',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:00',
                'updated_at' => '2024-12-10 16:08:00',
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'raúl.iglesias62',
                'email' => 'raúl.iglesias62@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4D4fi021rqHsFc1heFEwIeB5MIXm3AfGKmxnynObJ64Gdv/wzOizm',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:07:58',
                'updated_at' => '2024-12-10 16:07:58',
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'patricia.muñoz63',
                'email' => 'patricia.muñoz63@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$lGaaawxkx69Y38uumIUPnuV/3aSlR5DVn72ngJ.Xk6pCemsrqASIK',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:00',
                'updated_at' => '2024-12-10 16:08:00',
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'luis.serrano64',
                'email' => 'luis.serrano64@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$LOpOS4x5RX2Gp0ylQ.L1Zer9HpHHOvAmQHXWxf.Ryzo4Jmx9Bv4BS',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:01',
                'updated_at' => '2024-12-10 16:08:01',
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'antonio.gómez65',
                'email' => 'antonio.gómez65@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$LfrMj7pLewy1y55aiuMijeb6naf83Tk4jMl1P6Y.uw0dTn0evdDK2',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:02',
                'updated_at' => '2024-12-10 16:08:02',
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'marta.sánchez66',
                'email' => 'marta.sánchez66@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Mhkq3QiTF2I9evPD9GywH.iBa.8bTEe8bHKdiWOurshyfwO0mpMS6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:03',
                'updated_at' => '2024-12-10 16:08:03',
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'raúl.gil67',
                'email' => 'raúl.gil67@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$w/Ww25m9NYcFBuoqKtz9LurDs7cV0sRbp.kf2zfeKr1GWvQvYcd8a',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:04',
                'updated_at' => '2024-12-10 16:08:04',
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'ana.pérez68',
                'email' => 'ana.pérez68@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$z8zT74A00KDMFCBd6MmI3uxCws4DcHGCGiErId4ir2P8P07UUThlu',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:05',
                'updated_at' => '2024-12-10 16:08:05',
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'luis.gonzález69',
                'email' => 'luis.gonzález69@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nk9YCUgSYFx3GNShsbdiKu1e7Gbjai0KnWGLHIhSakPINEvdRJzYu',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:06',
                'updated_at' => '2024-12-10 16:08:06',
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'lucía.cruz70',
                'email' => 'lucía.cruz70@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$sydIh73Y6iJpv9q1B1Q22O7rDDNh14DwLriRdcOW4AyWGLHhJ74.G',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:07',
                'updated_at' => '2024-12-10 16:08:07',
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'carmen.torres71',
                'email' => 'carmen.torres71@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Vgx/eokQ6NYmyHj2J8bECOjh0lVkfyusfjG7PCjkbqnB3Ge7HyBqK',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:09',
                'updated_at' => '2024-12-10 16:08:09',
            ),
            77 => 
            array (
                'id' => 79,
                'name' => 'pedro.jiménez72',
                'email' => 'pedro.jiménez72@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jzqp8ZmNHGVCYpnwKd/1e.SCEnyUEgPyKMzqp71nplkuSdJhAEKni',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:10',
                'updated_at' => '2024-12-10 16:08:10',
            ),
            78 => 
            array (
                'id' => 80,
                'name' => 'carmen.hernández73',
                'email' => 'carmen.hernández73@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nUiujUbKo7qvb5yyo9RKQuUCCaze9q8WJ3UnjoUqtmb/Xx76PgYRy',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:12',
                'updated_at' => '2024-12-10 16:08:12',
            ),
            79 => 
            array (
                'id' => 81,
                'name' => 'juan.díaz74',
                'email' => 'juan.díaz74@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$G8gAVR8gNe9dK.Q3ih1UrO1Faz3nPLSRDS2yiAN3IZFP5qduAiNVq',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:13',
                'updated_at' => '2024-12-10 16:08:13',
            ),
            80 => 
            array (
                'id' => 82,
                'name' => 'isabel.paredes75',
                'email' => 'isabel.paredes75@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$xrNH9Zn.n0j1CzWNQwf2OuDblR/vFGC2x6jcx5Q/uUFKD1.G02EHa',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:14',
                'updated_at' => '2024-12-10 16:08:14',
            ),
            81 => 
            array (
                'id' => 83,
                'name' => 'pablo.martínez76',
                'email' => 'pablo.martínez76@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Zj7rrDrxTVCVmg2S5xeobePwyM.cbDyXj1R0.zLTUGlcal279aRE.',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:15',
                'updated_at' => '2024-12-10 16:08:15',
            ),
            82 => 
            array (
                'id' => 84,
                'name' => 'verónica.pascual77',
                'email' => 'verónica.pascual77@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$QF5euuiNShNeyOqFi83Sy.oKbFhzL2523h1EVEEsY3nzF0qKNj9Zy',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:16',
                'updated_at' => '2024-12-10 16:08:16',
            ),
            83 => 
            array (
                'id' => 85,
                'name' => 'raúl.ortíz78',
                'email' => 'raúl.ortíz78@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$AQSFWX6kUSDB5pupxokrC.Q/QjB/ZFpxrNS10lX8z154fbat0PexG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:17',
                'updated_at' => '2024-12-10 16:08:17',
            ),
            84 => 
            array (
                'id' => 86,
                'name' => 'carlos.moreno79',
                'email' => 'carlos.moreno79@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9eclafuuReJt541IvL1srOASQrHdNOuXGfS5r14zVzMAJvdcStc7q',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:18',
                'updated_at' => '2024-12-10 16:08:18',
            ),
            85 => 
            array (
                'id' => 87,
                'name' => 'isabel.sánchez80',
                'email' => 'isabel.sánchez80@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$aBe8aRlYQTR31nGCwScsX.YqNNeQZRD9fdCBUzcNh25wCb85lNEKy',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:19',
                'updated_at' => '2024-12-10 16:08:19',
            ),
            86 => 
            array (
                'id' => 88,
                'name' => 'elena.lópez81',
                'email' => 'elena.lópez81@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZhRT6JiOpmYGzPHQYnE2buynkLUEnnE5waAxiC7I28WvjJs6eP2U6',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:20',
                'updated_at' => '2024-12-10 16:08:20',
            ),
            87 => 
            array (
                'id' => 89,
                'name' => 'lucía.muñoz82',
                'email' => 'lucía.muñoz82@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$X2dbvRYfAjz8XkVgvIgsHOnxywX/Jie3biNfMC1aXQ4MvpWynXEfG',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:21',
                'updated_at' => '2024-12-10 16:08:21',
            ),
            88 => 
            array (
                'id' => 90,
                'name' => 'sara.marín83',
                'email' => 'sara.marín83@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mxmh60Bydpx9YbZ6zidOt.Ldp0UN9VrOL4YMTmh4Q0K4sNhQ3Cmki',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:22',
                'updated_at' => '2024-12-10 16:08:22',
            ),
            89 => 
            array (
                'id' => 91,
                'name' => 'andrés.gonzález84',
                'email' => 'andrés.gonzález84@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qzT6lKkVjzlNwKZV44CGUOWNJOUvwHu45E5oligQHhzpysLffrbFK',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:23',
                'updated_at' => '2024-12-10 16:08:23',
            ),
            90 => 
            array (
                'id' => 92,
                'name' => 'beatriz.cabrera85',
                'email' => 'beatriz.cabrera85@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$TGKvlxUA0dvgLE7WXdSN9eqptTkB2Zq517H0G0bVhdXruHaC2koS2',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:25',
                'updated_at' => '2024-12-10 16:08:25',
            ),
            91 => 
            array (
                'id' => 93,
                'name' => 'Álvaro.jiménez86',
                'email' => 'Álvaro.jiménez86@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$7C5ZLmyO2twpzC/GTuhI.OMcaqW1RYkWT2uzOUXKQ7hV9a2ce5wnW',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:26',
                'updated_at' => '2024-12-10 16:08:26',
            ),
            92 => 
            array (
                'id' => 94,
                'name' => 'beatriz.cabrera87',
                'email' => 'beatriz.cabrera87@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$eQV4/gOZc.fr7yRkzTn24eQ28SNPBC2Izu8tFIjoL4JMO1gw1gLsO',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:27',
                'updated_at' => '2024-12-10 16:08:27',
            ),
            93 => 
            array (
                'id' => 95,
                'name' => 'pedro.marín88',
                'email' => 'pedro.marín88@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$uY1toz/WegiXWg5XYNyOx.yEuifjk/p.Ub.jMEo.ahxKZWSnB8Jci',
                'remember_token' => NULL,
                'created_at' => '2024-12-10 16:08:28',
                'updated_at' => '2024-12-10 16:08:28',
            ),
        ));
        
        
    }
}