<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('users')->delete();
        
        DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'GianFranco',
                'email' => 'Gian@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$k1auoB0YUcXdcQihVTHmeuDR3irqL7hhp2cwWAiWKmlgd91o2hMOy',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 02:22:08',
                'updated_at' => '2024-08-15 04:04:59',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Jhonatan',
                'email' => 'Jm@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YwBp.OzykM3oke2f8kxgqe5Y1sDj0AnR4d7/e.OBCFELX0oDdSkye',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 02:22:41',
                'updated_at' => '2024-08-15 04:05:19',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Fabian Ruiz',
                'email' => 'fruiz@mail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PRO.GF7682LwQsGwuE3Jru.geBFdHAOSN7hzZxSz/765Lw2Ru30Ia',
                'remember_token' => NULL,
                'created_at' => '2024-08-15 06:40:55',
                'updated_at' => '2024-08-15 06:40:55',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Secretaria',
                'email' => 'secretaria@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.MYT.P7bnwPrQJeMKWEB9eiOnZUlz.DpShe/0kAMbC/EdJnVUc3nm',
                'remember_token' => NULL,
                'created_at' => '2024-11-21 05:53:17',
                'updated_at' => '2024-11-21 05:53:17',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Gian',
                'email' => 'gianfrancosr182015@gmail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mpwkq3sT5DsGERrxbb8Hmux7sjOLxPKHMKf/hC3kHROLtzlwGS/I2',
                'remember_token' => NULL,
                'created_at' => '2024-11-24 21:42:45',
                'updated_at' => '2024-11-24 21:43:58',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'PRUEBA',
                'email' => 'mail@mail.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4o3nfe4qNimZw.Sa.z8uf.T69xJvwz6eVJZaS9EMLtwprXlKKcv/a',
                'remember_token' => NULL,
                'created_at' => '2024-12-05 16:01:03',
                'updated_at' => '2024-12-05 16:01:03',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'lucía.moreno1',
                'email' => 'lucía.moreno1@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9853xOItOeKMQOIqipTL0eRyIBdSNZpHTXgHXHO6rHEksYSfLeKZ6',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:29',
                'updated_at' => '2024-12-11 02:56:29',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'carlos.méndez2',
                'email' => 'carlos.méndez2@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nB9rLwHDsi/iyQfRB1A83ONdFG87b19T61vyVQ0sbEEnhPusx.XSy',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:30',
                'updated_at' => '2024-12-11 02:56:30',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'sofía.navarro3',
                'email' => 'sofía.navarro3@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PGubyAkmNZcPxMZ4L0J4ZuPYaXiiVcSjEe9AyIKAcFY6TILp2yaVy',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:31',
                'updated_at' => '2024-12-11 02:56:31',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'sofía.muñoz4',
                'email' => 'sofía.muñoz4@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$uxJ2/uWLkwT9A44rGUxHu.DKpWwxv/dfyAZ3GDCrXVYb2t1Ga5evu',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:32',
                'updated_at' => '2024-12-11 02:56:32',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'ana.cabrera5',
                'email' => 'ana.cabrera5@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$KhlHc5wqJthAHjpzKyBPbOD7m5gkcB/6lrhF28xjmc5ERoB.oE/.O',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:33',
                'updated_at' => '2024-12-11 02:56:33',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'carmen.marín6',
                'email' => 'carmen.marín6@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jcHDq8RuFCz3L2mXyF/19OzxSP47p1gJ/GC6mbEEJjBE03sL8DUNm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:34',
                'updated_at' => '2024-12-11 02:56:34',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'carmen.gonzález7',
                'email' => 'carmen.gonzález7@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$kc2x5B/Np3QhugZDtKS2fOcVkjbFfryW7yLqxlZ3E9tNk5khr9uve',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:35',
                'updated_at' => '2024-12-11 02:56:35',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'ana.pascual8',
                'email' => 'ana.pascual8@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fRmkIM5m.HQF49.C8vYF0eRnksi61MXwLoxYyKj9rs2IY/0TdBZqe',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:36',
                'updated_at' => '2024-12-11 02:56:36',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'patricia.díaz9',
                'email' => 'patricia.díaz9@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$TWZzh2tFMrcgvd1v3P2Jk.2dFQMCLdkviIOZ6OjG2oeHh5SXU4k9C',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:37',
                'updated_at' => '2024-12-11 02:56:37',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'isabel.serrano10',
                'email' => 'isabel.serrano10@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9KCSKaW36IQbMVRWDnQEPO99smZVeHYTbGQ6HWltryz58e/Nqlx6G',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:38',
                'updated_at' => '2024-12-11 02:56:38',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'patricia.castro11',
                'email' => 'patricia.castro11@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8TshiwZMXJl0mumXPg5mfuw6th4jwOyl7gvhhadnFu87GBfWiExo2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:39',
                'updated_at' => '2024-12-11 02:56:39',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'juan.gómez12',
                'email' => 'juan.gómez12@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$h3DlcGR04sU.IAkOrCrpSuK43GBKa3kPVVVO8SOXQ8MtMWjfEMZ0S',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:40',
                'updated_at' => '2024-12-11 02:56:40',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'ana.cruz13',
                'email' => 'ana.cruz13@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$giBnXF.WIPmUTrIjdRM.huGsISclfs/GFxlfHjBOukjgciJSkh87G',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:41',
                'updated_at' => '2024-12-11 02:56:41',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'carmen.paredes14',
                'email' => 'carmen.paredes14@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Lp/ld6LGRhqsT7NdWSVG4ezG1BSEEBhkXQgULuLvglGIcxw2PUfaC',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:42',
                'updated_at' => '2024-12-11 02:56:42',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'juan.gil15',
                'email' => 'juan.gil15@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$h8bBK6RIZuEQ39Rio5beeeAFR4CMZzqilBksnJio8DkbnTULyAKNq',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:42',
                'updated_at' => '2024-12-11 02:56:42',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'ana.torres16',
                'email' => 'ana.torres16@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Bh0wTSEZggukMm9veMaRtuGaWsuyxFdA8uunNnxNUmDt0AHDCLU.2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:43',
                'updated_at' => '2024-12-11 02:56:43',
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'javier.salazar17',
                'email' => 'javier.salazar17@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YvHxOX4vsOgT96EHOCYsQOxm86JlmP4bZdBijHJCGO6fyRr7xAilS',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:44',
                'updated_at' => '2024-12-11 02:56:44',
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'carmen.lópez18',
                'email' => 'carmen.lópez18@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$14pbQROdOeIL9mgUxsQ0wOQLs.WB76RUcbTdOz4bWwzkwi5h6mu4a',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:45',
                'updated_at' => '2024-12-11 02:56:45',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'marta.ramírez19',
                'email' => 'marta.ramírez19@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Mi0aMVVyIRXL4ejkzWm0NuOlm60CMjSVjFm9Sebr1mF7XHDRQo.5S',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:46',
                'updated_at' => '2024-12-11 02:56:46',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'maría.sánchez20',
                'email' => 'maría.sánchez20@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$sR2EFFEIlAImnVJFqdtW/uFYqhERjH60aAYd6KGcvZ5HmWhsaV7r.',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:47',
                'updated_at' => '2024-12-11 02:56:47',
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'juan.muñoz21',
                'email' => 'juan.muñoz21@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YNquRm/hpyRRkgDBZ.GSlOMBScDfc1rpbCLv29Ec2pVcS8WAcbr2y',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:48',
                'updated_at' => '2024-12-11 02:56:48',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'Álvaro.vázquez22',
                'email' => 'Álvaro.vázquez22@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2mCcplTWzZWcaCp3DIyDEOeomh5i/FdEAYbca7Mw1L1PPpGqw.g56',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:49',
                'updated_at' => '2024-12-11 02:56:49',
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'beatriz.serrano23',
                'email' => 'beatriz.serrano23@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$rBS.vL9gyn0OYNY1AbBpX.xS0YqhbqVhA7FPAV0ycvSqJ0ag9y4gm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:50',
                'updated_at' => '2024-12-11 02:56:50',
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'sofía.gil24',
                'email' => 'sofía.gil24@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GyTm2AM5Ip/ZdZ4gn291K.bjbwsYQcCM1hZfm.lgasoopO8SEgh9e',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:51',
                'updated_at' => '2024-12-11 02:56:51',
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'juan.díaz25',
                'email' => 'juan.díaz25@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$0mUUR3htVrteRsYrtAB5jOyOIBn5GczP7u7c6L.x.Au6HFAIGWWai',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:53',
                'updated_at' => '2024-12-11 02:56:53',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'sofía.cabrera26',
                'email' => 'sofía.cabrera26@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$FFncXTNZAM3CyVOQ4GrAnOBI5inIIAL8LuaD9Osxrzck/PoaipwS2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:54',
                'updated_at' => '2024-12-11 02:56:54',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'felipe.jiménez27',
                'email' => 'felipe.jiménez27@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Pohy3haABw5X9U6GmIJZnOqMIRKuaNea0AzlXyjzwgIVi6g24dL0O',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:55',
                'updated_at' => '2024-12-11 02:56:55',
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'beatriz.méndez28',
                'email' => 'beatriz.méndez28@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$RFQ9dgKg4k1F6osWH2oLfurNdjwo7rEU0Q8F9UiKZeBmnP4p.f8Nu',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:56',
                'updated_at' => '2024-12-11 02:56:56',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'andrés.cruz29',
                'email' => 'andrés.cruz29@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4jm4Jm4jq1Fb2cCbTCIZiO4m7SwU9K/MGBOUtZpabhpe4EVKdeyU2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:57',
                'updated_at' => '2024-12-11 02:56:57',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'ricardo.marín30',
                'email' => 'ricardo.marín30@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$BkXXzTueGRUrS7R0eNNSi./oIdQDktB9NxfAkreoZV.ntf9jFGwOK',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:58',
                'updated_at' => '2024-12-11 02:56:58',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'pedro.ramos31',
                'email' => 'pedro.ramos31@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$7Qkx.350Nsmnmvr1ttfgBOvqiUjbyfJdIKXzcJHhVJIxxBNXmCe3S',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:56:59',
                'updated_at' => '2024-12-11 02:56:59',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'patricia.moreno32',
                'email' => 'patricia.moreno32@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$uU13D3lR3ZCpCewSYItcNuA1sG5UFRApohlbAnRQOiVX2ur2D266i',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:00',
                'updated_at' => '2024-12-11 02:57:00',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'isabel.vázquez33',
                'email' => 'isabel.vázquez33@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$VCXNR7UdT.m//wMPart5IOqBrT63n9Sj60.Ouokxwhx9BKBboX0Bm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:01',
                'updated_at' => '2024-12-11 02:57:01',
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'raúl.martínez34',
                'email' => 'raúl.martínez34@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$hf4ouTwM0lAOt39uCU3em.MM9UHZzj60oQcqD3.DJuQCNlx0nr7eO',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:02',
                'updated_at' => '2024-12-11 02:57:02',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'laura.ramírez35',
                'email' => 'laura.ramírez35@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.DqCIQlDhlO7qI7Zyn.SiebSP014xYsUiVikynfY4R4wK2qYZvPMG',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:03',
                'updated_at' => '2024-12-11 02:57:03',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'ricardo.Álvarez36',
                'email' => 'ricardo.Álvarez36@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3hhm4IkPf1Hb8vmgVdoiTuMiiPdvz9Io5zPtXFDjrcFYNrIQVRD8.',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:04',
                'updated_at' => '2024-12-11 02:57:04',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'josé.marín37',
                'email' => 'josé.marín37@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jiQcE1NGAb4v5XWqwyuq.uycgp9q23k5O1ClOmGMIJJaZ376oHJKW',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:05',
                'updated_at' => '2024-12-11 02:57:05',
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'josé.sánchez38',
                'email' => 'josé.sánchez38@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NUSJNsC.TZB6TgnhvhlmeeFqFqa9NnSegM97T07iR6f7PezpxmM46',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:06',
                'updated_at' => '2024-12-11 02:57:06',
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'fernando.moreno39',
                'email' => 'fernando.moreno39@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$gntd7VcHmTkOdIMgkdvoJOrWx6sWBjFDUzr/mWUDv1XdHHJfZn5Xe',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:07',
                'updated_at' => '2024-12-11 02:57:07',
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Álvaro.hernández40',
                'email' => 'Álvaro.hernández40@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$lOMHABWVawSkmrUH5kNPs.ak1ktZ7pLozK5cbEkkCVi1INJM35xkG',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:08',
                'updated_at' => '2024-12-11 02:57:08',
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'elena.vázquez41',
                'email' => 'elena.vázquez41@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$D/pTXRKDunyx3J/ENcZjuelC6xGEr71GpZteulvIG4Gr9YYtPd8PO',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:09',
                'updated_at' => '2024-12-11 02:57:09',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'clara.martínez42',
                'email' => 'clara.martínez42@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$J72eCgO73Au3OVCF4tF1IekHzYjiMwflKI7hmB7RjZ8wvb.lLToGW',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:10',
                'updated_at' => '2024-12-11 02:57:10',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'josé.cruz43',
                'email' => 'josé.cruz43@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mtX7aFl9MS9R.ljoAjTxveDZ9a.1fcpTUBlrFot51DsEK3sbyB.eC',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:11',
                'updated_at' => '2024-12-11 02:57:11',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'javier.gonzález44',
                'email' => 'javier.gonzález44@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$A0bAz5iw2Av59lsBi1Y66esggcpDzHwv5zoTAiSR/P8WUzSP1MgHW',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:12',
                'updated_at' => '2024-12-11 02:57:12',
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'sara.méndez45',
                'email' => 'sara.méndez45@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NAWxGxQP6yD9tUG1y6hyCOgLvHw.Lw6p5790F32I0h5DSDgmJnYqG',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:13',
                'updated_at' => '2024-12-11 02:57:13',
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'luis.pérez46',
                'email' => 'luis.pérez46@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$fy/YMkZygpvJ8onFcUiBaO451sBHG.KEgA6vy8pl0.CmElcUHxjXG',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:13',
                'updated_at' => '2024-12-11 02:57:13',
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'pablo.paredes47',
                'email' => 'pablo.paredes47@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$vP9f/nxJwoOsz91GlkWI5e/Z.x24AWp6DmDjZCb80F/lcKUXYEE/O',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:14',
                'updated_at' => '2024-12-11 02:57:14',
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'lucía.paredes48',
                'email' => 'lucía.paredes48@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qo.mlKlhRfmL.22CNrg/keakJuRNP3FYr2r3pHPXfURjW6k29VZhO',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:15',
                'updated_at' => '2024-12-11 02:57:15',
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'beatriz.ortíz49',
                'email' => 'beatriz.ortíz49@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ap/tXOhjDk4rCDgSDuCGcO6R2RGAwK3oPJXdc5yFXaB8VlJKFs8SC',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:16',
                'updated_at' => '2024-12-11 02:57:16',
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'clara.castro50',
                'email' => 'clara.castro50@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$VPNLCXdG449dbskoo6.5ze8hUQ6hLB0wr33iaObvH0AqnOLW5OvXq',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:17',
                'updated_at' => '2024-12-11 02:57:17',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'lucía.hernández51',
                'email' => 'lucía.hernández51@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6uG1fuoGd/UIU3dnQdo3eu1bQvlco7xR01F0psC7ID69G1muij1Ny',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:19',
                'updated_at' => '2024-12-11 02:57:19',
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'verónica.díaz52',
                'email' => 'verónica.díaz52@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3KnuxWA2eR2ZH9uuCachmehgDx8Mte4UiZ3Ute23ZsxpCMrPye/vW',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:20',
                'updated_at' => '2024-12-11 02:57:20',
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'luis.castro53',
                'email' => 'luis.castro53@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$5K7/DMPUNLH2/cxk7pnWGOnUESKeU.0XkdGmxEfsNr62KcZKmHLUa',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:21',
                'updated_at' => '2024-12-11 02:57:21',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'ricardo.pascual54',
                'email' => 'ricardo.pascual54@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$BMhclVTDVs1.Vp5ZEzRbyeCmxfNIQKkGw9ts0WWX43t5l9UKNsU8i',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:22',
                'updated_at' => '2024-12-11 02:57:22',
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'david.lópez55',
                'email' => 'david.lópez55@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2cw3iJQoETsrqbf45ud41uIUndkc.Rt3DZRoOQ/YYslObLHDFPKU2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:23',
                'updated_at' => '2024-12-11 02:57:23',
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'sara.sánchez56',
                'email' => 'sara.sánchez56@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$VR/9lYl/1Kb3du1LziSh6es/Dh1txQNBYfRpDfDUvAzXCa1dPHid2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:24',
                'updated_at' => '2024-12-11 02:57:24',
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'Álvaro.martínez57',
                'email' => 'Álvaro.martínez57@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$TdJUPUkwXsFVRvsUhGiNbuRPzEgagYIlKb89Fv7LrwlEX/lcRd3Xm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:25',
                'updated_at' => '2024-12-11 02:57:25',
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'javier.serrano58',
                'email' => 'javier.serrano58@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8yakihYe8GcLvNZg1W0ZXeWFLAudblXyNbi/6CFVvgM6urpKb5t2m',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:26',
                'updated_at' => '2024-12-11 02:57:26',
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'marta.ramírez59',
                'email' => 'marta.ramírez59@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$MSXVEGglU0E58lVxUw.vduJ.SMG3V6KL7T9ctWj0pO.O1.TLN.ADK',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:27',
                'updated_at' => '2024-12-11 02:57:27',
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'luis.ruiz60',
                'email' => 'luis.ruiz60@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.5/GHzn/jxLwNgQHaKzw.6nJagXU66tttxqlKHAxSu/vUIgP1aI2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:29',
                'updated_at' => '2024-12-11 02:57:29',
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'isabel.pérez61',
                'email' => 'isabel.pérez61@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$HVv2CWL7dwl8HPlH2iH3bOWGfMCf3aCn3e3nzXE17rtS/k3xyID8W',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:30',
                'updated_at' => '2024-12-11 02:57:30',
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'isabel.hernández62',
                'email' => 'isabel.hernández62@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$T0hIAlZSzKB4LPmxeNZ0A.51oXNoP2Q6Jl1A7uboM9fBVfn5zlNyy',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:31',
                'updated_at' => '2024-12-11 02:57:31',
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'javier.marín63',
                'email' => 'javier.marín63@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$z4k0JI0.jFJ.psyjuxSrQOrf98G90U1xmUQ6h5XG/c8BS0n1ezUN2',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:32',
                'updated_at' => '2024-12-11 02:57:32',
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'juan.hernández64',
                'email' => 'juan.hernández64@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.9vHQ9YjhJjkFOU8d8vA9ue6TTyQnDar57fRcqLZMy3mxLKunU49a',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:34',
                'updated_at' => '2024-12-11 02:57:34',
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'raúl.ortíz65',
                'email' => 'raúl.ortíz65@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2c37uNqq1GcexNMlEuxKmOV1w6eu1XeInLlaWvUSBzcRaBVoPj39W',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:35',
                'updated_at' => '2024-12-11 02:57:35',
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'victoria.méndez66',
                'email' => 'victoria.méndez66@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$afEi4HhScNFGbp5gt3BfMerbTlUhMng2XVbHmxOCqnhhBYZQuA8Fa',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:36',
                'updated_at' => '2024-12-11 02:57:36',
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'beatriz.serrano67',
                'email' => 'beatriz.serrano67@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Pv4vF0oOxyWZNN8SP.FMAelkzuBVY8Sl1q8sDUtNjg8sOVWzNmCU.',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:37',
                'updated_at' => '2024-12-11 02:57:37',
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'lucía.Álvarez68',
                'email' => 'lucía.Álvarez68@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nRhRJbmVvS1J/sbKTmIjJuzSwFT.m415qGKPQlxs4Qb8.mtI5miqu',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:38',
                'updated_at' => '2024-12-11 02:57:38',
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'pablo.pascual69',
                'email' => 'pablo.pascual69@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$EwyAbrJvyvyYlPR03ojdIuDbR5t/lMoV/6lQ.ilwYtJTxffbiXh52',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:39',
                'updated_at' => '2024-12-11 02:57:39',
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'verónica.cruz70',
                'email' => 'verónica.cruz70@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ww88JT2HXQ1aANVWerthFunM4NgMBjYwtB3BN5P.IbXAHAShjxfzK',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:41',
                'updated_at' => '2024-12-11 02:57:41',
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'ricardo.paredes71',
                'email' => 'ricardo.paredes71@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$sqzCSGINu1H89vGeozpY8uNn4AdfcJEhgNV0HE2CIf5DwezMdPLsi',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:42',
                'updated_at' => '2024-12-11 02:57:42',
            ),
            77 => 
            array (
                'id' => 79,
                'name' => 'ana.cabrera72',
                'email' => 'ana.cabrera72@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OrVPENANRidL7TM.ubI3A.bjB.S9UzBNz0gqNS1dsVcS9rUiaDcgm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:43',
                'updated_at' => '2024-12-11 02:57:43',
            ),
            78 => 
            array (
                'id' => 80,
                'name' => 'isabel.gil73',
                'email' => 'isabel.gil73@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IOp44tuav45uB9HsN5ebYOmLenCGDRugyHhxjCRk8su3jCa7sjspC',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:44',
                'updated_at' => '2024-12-11 02:57:44',
            ),
            79 => 
            array (
                'id' => 81,
                'name' => 'luis.cruz74',
                'email' => 'luis.cruz74@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$eRoN4T8rbwa0GUsY64PCYuE5BrlhEB.3LATBun.JrSQEhBuKskKuq',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:43',
                'updated_at' => '2024-12-11 02:57:43',
            ),
            80 => 
            array (
                'id' => 82,
                'name' => 'maría.muñoz75',
                'email' => 'maría.muñoz75@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Somfat3FtXiGYCLMmoy6ceKjAaH01xS8PTOF6jDveqSQWWxuxlcEO',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:45',
                'updated_at' => '2024-12-11 02:57:45',
            ),
            81 => 
            array (
                'id' => 83,
                'name' => 'ana.méndez76',
                'email' => 'ana.méndez76@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$5qxcPxQ9/cwAx60gT5ALQ.99LVZAp4t1fS6n.Nyb2dVH5coHQRtma',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:46',
                'updated_at' => '2024-12-11 02:57:46',
            ),
            82 => 
            array (
                'id' => 84,
                'name' => 'sara.paredes77',
                'email' => 'sara.paredes77@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Idl.8w/xMRs3CWRdN6FQGuAQIrNk3msrb0PAEpM7oTqAZH6OVGnVO',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:47',
                'updated_at' => '2024-12-11 02:57:47',
            ),
            83 => 
            array (
                'id' => 85,
                'name' => 'luis.marín78',
                'email' => 'luis.marín78@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pZ.LWWHk2SxpaXD5h0Y03.McU6GrI1a4m.PUQg7uPuFgwXb5kGeXm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:48',
                'updated_at' => '2024-12-11 02:57:48',
            ),
            84 => 
            array (
                'id' => 86,
                'name' => 'felipe.lópez79',
                'email' => 'felipe.lópez79@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$lXmIxrpjF3KfNTXhLHWs/u812UUDOOunoRnXWs0v2XOOx0nlW8m06',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:49',
                'updated_at' => '2024-12-11 02:57:49',
            ),
            85 => 
            array (
                'id' => 87,
                'name' => 'pablo.paredes80',
                'email' => 'pablo.paredes80@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$hjZrz9mVZRX.bn9LtbkfDuMoL.qJLH/tqul3Ckp.SnFOf/pcBYA5O',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:50',
                'updated_at' => '2024-12-11 02:57:50',
            ),
            86 => 
            array (
                'id' => 88,
                'name' => 'javier.cabrera81',
                'email' => 'javier.cabrera81@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$wOmu23LbtPqieV7OH6o.K.66Y0g/U/6T3RNHohyojUg0Wm6MpQU7q',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:51',
                'updated_at' => '2024-12-11 02:57:51',
            ),
            87 => 
            array (
                'id' => 89,
                'name' => 'sofía.jiménez82',
                'email' => 'sofía.jiménez82@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$829jAU3kql64wPE9/OzfyexsVTpgIsiqcg8WrFdCP/hT3mcAw2LuC',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:52',
                'updated_at' => '2024-12-11 02:57:52',
            ),
            88 => 
            array (
                'id' => 90,
                'name' => 'ricardo.serrano83',
                'email' => 'ricardo.serrano83@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$VJH8ySnhT/aVSFmWMbaAouGL.jA50VarbhsQbTD3QHdIwbVxcUAWm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:53',
                'updated_at' => '2024-12-11 02:57:53',
            ),
            89 => 
            array (
                'id' => 91,
                'name' => 'luis.jiménez84',
                'email' => 'luis.jiménez84@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NaYsEsedXQq/aIbtWwbzW.Nf1OL1wRfz.0pnvWLtBxM7WX2REeDti',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:54',
                'updated_at' => '2024-12-11 02:57:54',
            ),
            90 => 
            array (
                'id' => 92,
                'name' => 'luis.ramírez85',
                'email' => 'luis.ramírez85@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nUditcLr/KojD0Oa4lrTu.wX6W0soSjXB83JOqbUo7F/Sy9zqAhRm',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:55',
                'updated_at' => '2024-12-11 02:57:55',
            ),
            91 => 
            array (
                'id' => 93,
                'name' => 'andrés.cruz86',
                'email' => 'andrés.cruz86@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ata85AC/jOokuIAUaoXr3.Jqz6r0sfMC/Z2LFnwRcLNEoRNX1TgX.',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:57',
                'updated_at' => '2024-12-11 02:57:57',
            ),
            92 => 
            array (
                'id' => 94,
                'name' => 'verónica.pérez87',
                'email' => 'verónica.pérez87@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$AFXzifwm9Asr7fcQDyrpDesWFMNCDwTn9bA5ILdO6YePEuS5DMY/G',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:57:59',
                'updated_at' => '2024-12-11 02:57:59',
            ),
            93 => 
            array (
                'id' => 95,
                'name' => 'ricardo.ruiz88',
                'email' => 'ricardo.ruiz88@example.com',
                'profile_photo' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$7sBoM2CKj83/MPVxRjJhWeoSQMcvAVnyGfZstkefAFKQGmfyq/oQK',
                'remember_token' => NULL,
                'created_at' => '2024-12-11 02:58:01',
                'updated_at' => '2024-12-11 02:58:01',
            ),
        ));
        
        
    }
}